// <auto-generated />
using System;
using FundManager.DataAccess.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FundManager.DataAccess.Migrations
{
    [DbContext(typeof(FundManagerDbContext))]
    partial class FundManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.ApplicationImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OutletId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "The Grand Ho Tram Logo",
                            FileExtension = ".png",
                            FilePath = "/ApplicationImages/TheGrandHoTramLogo.png",
                            FileSize = 3100L,
                            FileUrl = "/ApplicationImages/16831151-1e2c-4f27-bc56-1a26c3afef0f.jpg",
                            IsActive = true,
                            IsDelete = false,
                            Name = "The Grand Ho Tram",
                            Type = (byte)2,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "The Grand Spa",
                            FileExtension = ".png",
                            FilePath = "/ApplicationImages/ed572294-335b-46bd-8df8-99de63864904.png",
                            FileSize = 13050L,
                            FileUrl = "/ApplicationImages/ed572294-335b-46bd-8df8-99de63864904.png",
                            IsActive = true,
                            IsDelete = false,
                            Name = "The Grand Spa Icon",
                            OutletId = 1,
                            PropertyId = 2,
                            Type = (byte)0,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Lotus Spa Logo",
                            FileExtension = ".png",
                            FilePath = "/ApplicationImages/70de369b-60ee-4aaf-85b0-04b8ad623991.png",
                            FileSize = 11465L,
                            FileUrl = "/ApplicationImages/70de369b-60ee-4aaf-85b0-04b8ad623991.png",
                            IsActive = true,
                            IsDelete = false,
                            Name = "Lotus Spa Icon",
                            OutletId = 2,
                            PropertyId = 1,
                            Type = (byte)0,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "MAIA SPA Icon",
                            FileExtension = ".png",
                            FilePath = "/ApplicationImages/ede11902-62a8-4e76-859f-2312b0c24893.png",
                            FileSize = 12176L,
                            FileUrl = "/ApplicationImages/ede11902-62a8-4e76-859f-2312b0c24893.png",
                            IsActive = true,
                            IsDelete = false,
                            Name = "MAIA SPA Icon",
                            OutletId = 3,
                            PropertyId = 3,
                            Type = (byte)0,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "The Grand Spa Image",
                            FileExtension = ".png",
                            FilePath = "/ApplicationImages/3cc52c88-5c58-481e-9f5a-533152911041.png",
                            FileSize = 1003615L,
                            FileUrl = "/ApplicationImages/3cc52c88-5c58-481e-9f5a-533152911041.png",
                            IsActive = true,
                            IsDelete = false,
                            Name = "The Grand Spa Image",
                            OutletId = 1,
                            PropertyId = 1,
                            Type = (byte)0,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Lotus Spa Image",
                            FileExtension = ".png",
                            FilePath = "/ApplicationImages/ab90af7f-6576-4f63-bce8-bae4d687de0b.png",
                            FileSize = 551515L,
                            FileUrl = "/ApplicationImages/ab90af7f-6576-4f63-bce8-bae4d687de0b.png",
                            IsActive = true,
                            IsDelete = false,
                            Name = "Lotus Spa Image",
                            OutletId = 1,
                            PropertyId = 1,
                            Type = (byte)0,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Maia Spa Image",
                            FileExtension = ".png",
                            FilePath = "/ApplicationImages/be451c4b-e9d3-44d3-834c-28b94c352353.png",
                            FileSize = 844391L,
                            FileUrl = "/ApplicationImages/be451c4b-e9d3-44d3-834c-28b94c352353.png",
                            IsActive = true,
                            IsDelete = false,
                            Name = "Maia Spa Image",
                            OutletId = 1,
                            PropertyId = 1,
                            Type = (byte)0,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "English Flag",
                            FileExtension = ".svg",
                            FilePath = "D:\\IIS Publish\\DigitalDocumentPlatform\\FundManager.API\\ApplicationImages\\bf6f69ff-9957-4faf-8524-6833eb96e3f9.svg",
                            FileSize = 1274L,
                            FileUrl = "/ApplicationImages/bf6f69ff-9957-4faf-8524-6833eb96e3f9.svg",
                            IsActive = true,
                            IsDelete = false,
                            Name = "English Flag",
                            Type = (byte)4,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Vietnam Flag",
                            FileExtension = ".svg",
                            FilePath = "D:\\IIS Publish\\DigitalDocumentPlatform\\FundManager.API\\ApplicationImages\\6640af6d-60a0-4cea-98c8-1871e7facb0e.svg",
                            FileSize = 1274L,
                            FileUrl = "/ApplicationImages/6640af6d-60a0-4cea-98c8-1871e7facb0e.svg",
                            IsActive = true,
                            IsDelete = false,
                            Name = "Vietnam Flag",
                            Type = (byte)4,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Korean Flag",
                            FileExtension = ".svg",
                            FilePath = "D:\\IIS Publish\\DigitalDocumentPlatform\\FundManager.API\\ApplicationImages\\f4bb608f-5a36-4b58-9959-c3361228a7ee.svg",
                            FileSize = 1274L,
                            FileUrl = "/ApplicationImages/f4bb608f-5a36-4b58-9959-c3361228a7ee.svg",
                            IsActive = true,
                            IsDelete = false,
                            Name = "Korean Flag",
                            Type = (byte)4,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "China Flag",
                            FileExtension = ".svg",
                            FilePath = "D:\\IIS Publish\\DigitalDocumentPlatform\\FundManager.API\\ApplicationImages\\d350d454-b583-4725-b20f-7c1a0e03d51b.svg",
                            FileSize = 1274L,
                            FileUrl = "/ApplicationImages/d350d454-b583-4725-b20f-7c1a0e03d51b.svg",
                            IsActive = true,
                            IsDelete = false,
                            Name = "China Flag",
                            Type = (byte)4,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.ApplicationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "System",
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DataType = "Integer",
                            Description = "Delay duration after submission in minutes.",
                            IsActive = true,
                            IsDelete = false,
                            Key = "DelayDurationAfterSubmitted",
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System",
                            Value = "10"
                        });
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("UserName")
                        .HasDatabaseName("IX_AuditLogs_UserName");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_Entity");

                    b.HasIndex("IsSuccess", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_Success")
                        .HasFilter("[IsSuccess] = 0");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WindowAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Department = "IT",
                            Email = "adminTemp@thegrandhotram.com",
                            EmployeeCode = "admin",
                            FullName = "System Administrator",
                            IsActive = true,
                            IsDelete = false,
                            PhoneNumber = "System",
                            Position = "Administrator",
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System",
                            WindowAccount = "admin"
                        });
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.EmployeeRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("EmployeeId", "RoleId")
                        .IsUnique();

                    b.ToTable("EmployeeRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            EmployeeId = 1,
                            IsActive = true,
                            IsDelete = false,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("StaffDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StaffDeviceId")
                        .HasDatabaseName("IX_Notifications_StaffDeviceId");

                    b.HasIndex("SessionId", "StaffDeviceId")
                        .HasDatabaseName("IX_Notifications_SessionStaff");

                    b.HasIndex("Status", "AttemptCount", "StaffDeviceId")
                        .HasDatabaseName("IX_Notifications_Pending")
                        .HasFilter("[Status] = 'Pending'");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "AttemptCount", "StaffDeviceId"), new[] { "Id", "SessionId", "PayloadJson", "CreatedAt" });

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionCode")
                        .IsUnique()
                        .HasFilter("[PermissionCode] IS NOT NULL");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Employee",
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "View dashboard",
                            IsActive = true,
                            IsDelete = false,
                            PermissionCode = "CAN_VIEW_DASHBOARD",
                            PermissionName = "View Dashboard",
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Employee",
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "View room check information",
                            IsActive = true,
                            IsDelete = false,
                            PermissionCode = "CAN_CHECK_ROOM",
                            PermissionName = "Room Check",
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Employee",
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Update employee information",
                            IsActive = true,
                            IsDelete = false,
                            PermissionCode = "CAN_UNCHECK",
                            PermissionName = "Un-check",
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Employee",
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "View history information",
                            IsActive = true,
                            IsDelete = false,
                            PermissionCode = "CAN_VIEW_HISTORY",
                            PermissionName = "History",
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Employee",
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "View reports",
                            IsActive = true,
                            IsDelete = false,
                            PermissionCode = "CAN_VIEW_REPORTS",
                            PermissionName = "Reports",
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Employee",
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "View all reports",
                            IsActive = true,
                            IsDelete = false,
                            PermissionCode = "CAN_VIEW_ALL_REPORTS",
                            PermissionName = "ViewAllReports",
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Full system access",
                            IsActive = true,
                            IsDelete = false,
                            RoleName = "Administrator",
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Management level access",
                            IsActive = true,
                            IsDelete = false,
                            RoleName = "OutletStaff",
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsActive = true,
                            IsDelete = false,
                            PermissionId = 1,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsActive = true,
                            IsDelete = false,
                            PermissionId = 2,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsActive = true,
                            IsDelete = false,
                            PermissionId = 3,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsActive = true,
                            IsDelete = false,
                            PermissionId = 4,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsActive = true,
                            IsDelete = false,
                            PermissionId = 5,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsActive = true,
                            IsDelete = false,
                            PermissionId = 6,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.EmployeeRole", b =>
                {
                    b.HasOne("FundManager.DataAccess.EntityModels.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FundManager.DataAccess.EntityModels.Role", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.RolePermission", b =>
                {
                    b.HasOne("FundManager.DataAccess.EntityModels.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FundManager.DataAccess.EntityModels.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.Employee", b =>
                {
                    b.Navigation("EmployeeRoles");
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FundManager.DataAccess.EntityModels.Role", b =>
                {
                    b.Navigation("EmployeeRoles");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
