export const PAGE_TITLES = {
    DASHBOARD: "Dashboard",
    REPORTS: "Reports",
    SETTINGS: "Settings",
    SYSTEM_SETTINGS: "System Settings",
    REGISTRATION: "Registration Management",
    DEVICE_MAPPING: "Device Mapping Settings",
    AUDIT_LOGS: "Audit Logs",
    ROLES: "Role Management",
    PERMISSIONS: "Permission Management",
    EMPLOYEES: "Employee Management",
    ENROLL_MEMBERSHIP_LOGS: "Enrollment Player Logs",
    MANAGE_DEVICES: "Device Management",
    CUSTOMER_SIGNED_DOCUMENTS: "Signed Customers",
    CUSTOMER_VERIFICATION_DOCUMENTS: "Customer Verification Documents",
    INCOME_DOCUMENTS_MIGRATION: "Income Documents Migration",
    DEFAULT: "Queue Management System",
    FORM_TEMPLATES: "Form Template Management",
    WORKFLOW: "Workflow Management",
    DOCUMENT_TEMPLATES: "Document Template Management",
    APPLICATION_IMAGE_MANAGEMENT: "Application Image Management",
    OUTLET_MANAGEMENT: "Outlet Management",
    PROPERTY_MANAGEMENT: "Property Management",
    MASTER_DATA: "Master Data Management",
} as const;