using DigitalDocumentPlatform.DataAccess.EntityModels;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DigitalDocumentPlatform.DataAccess.Initalizer
{
    public static class CountrySeed
    {
        public static void Seed(EntityTypeBuilder<Country> builder)
        {
            var seedAt = new DateTime(2026, 05, 19, 0, 0, 0, DateTimeKind.Utc);

            builder.HasData(
            new Country { Id = 4, Name = "Afghanistan", Description = "Afghanistan", Abrv2 = "AF", Abrv3 = "AFG", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 248, Name = "Aland Islands", Description = "Aland Islands", Abrv2 = "AX", Abrv3 = "ALA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 8, Name = "Albania", Description = "Albania", Abrv2 = "AL", Abrv3 = "ALB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 12, Name = "Algeria", Description = "Algeria", Abrv2 = "DZ", Abrv3 = "DZA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 16, Name = "American Samoa", Description = "American Samoa", Abrv2 = "AS", Abrv3 = "ASM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 20, Name = "Andorra", Description = "Andorra", Abrv2 = "AD", Abrv3 = "AND", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 24, Name = "Angola", Description = "Angola", Abrv2 = "AO", Abrv3 = "AGO", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 660, Name = "Anguilla", Description = "Anguilla", Abrv2 = "AI", Abrv3 = "AIA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 10, Name = "Antarctica", Description = "Antarctica", Abrv2 = "AQ", Abrv3 = "ATA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 28, Name = "Antigua and Barbuda", Description = "Antigua and Barbuda", Abrv2 = "AG", Abrv3 = "ATG", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 32, Name = "Argentina", Description = "Argentina", Abrv2 = "AR", Abrv3 = "ARG", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 51, Name = "Armenia", Description = "Armenia", Abrv2 = "AM", Abrv3 = "ARM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 533, Name = "Aruba", Description = "Aruba", Abrv2 = "AW", Abrv3 = "ABW", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 36, Name = "Australia", Description = "Australia", Abrv2 = "AU", Abrv3 = "AUS", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 40, Name = "Austria", Description = "Austria", Abrv2 = "AT", Abrv3 = "AUT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 31, Name = "Azerbaijan", Description = "Azerbaijan", Abrv2 = "AZ", Abrv3 = "AZE", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 44, Name = "Bahamas", Description = "Bahamas", Abrv2 = "BS", Abrv3 = "BHS", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 48, Name = "Bahrain", Description = "Bahrain", Abrv2 = "BH", Abrv3 = "BHR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 50, Name = "Bangladesh", Description = "Bangladesh", Abrv2 = "BD", Abrv3 = "BGD", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 52, Name = "Barbados", Description = "Barbados", Abrv2 = "BB", Abrv3 = "BRB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 112, Name = "Belarus", Description = "Belarus", Abrv2 = "BY", Abrv3 = "BLR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 56, Name = "Belgium", Description = "Belgium", Abrv2 = "BE", Abrv3 = "BEL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 84, Name = "Belize", Description = "Belize", Abrv2 = "BZ", Abrv3 = "BLZ", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 204, Name = "Benin", Description = "Benin", Abrv2 = "BJ", Abrv3 = "BEN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 60, Name = "Bermuda", Description = "Bermuda", Abrv2 = "BM", Abrv3 = "BMU", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 64, Name = "Bhutan", Description = "Bhutan", Abrv2 = "BT", Abrv3 = "BTN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 68, Name = "Bolivia", Description = "Bolivia", Abrv2 = "BO", Abrv3 = "BOL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 69, Name = "Bonaire, Sint Eustatius and Saba", Description = "Bonaire, Sint Eustatius and Saba", Abrv2 = "BQ", Abrv3 = "BES", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 70, Name = "Bosnia and Herzegovina", Description = "Bosnia and Herzegovina", Abrv2 = "BA", Abrv3 = "BIH", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 72, Name = "Botswana", Description = "Botswana", Abrv2 = "BW", Abrv3 = "BWA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 74, Name = "Bouvet Island", Description = "Bouvet Island", Abrv2 = "BV", Abrv3 = "BVT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 76, Name = "Brazil", Description = "Brazil", Abrv2 = "BR", Abrv3 = "BRA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 86, Name = "British Indian Ocean Territory", Description = "British Indian Ocean Territory", Abrv2 = "IO", Abrv3 = "IOT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 96, Name = "Brunei Darussalam", Description = "Brunei Darussalam", Abrv2 = "BN", Abrv3 = "BRN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 100, Name = "Bulgaria", Description = "Bulgaria", Abrv2 = "BG", Abrv3 = "BGR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 854, Name = "Burkina Faso", Description = "Burkina Faso", Abrv2 = "BF", Abrv3 = "BFA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 108, Name = "Burundi", Description = "Burundi", Abrv2 = "BI", Abrv3 = "BDI", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 132, Name = "Cabo Verde", Description = "Cabo Verde", Abrv2 = "CV", Abrv3 = "CPV", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 116, Name = "Cambodia", Description = "Cambodia", Abrv2 = "KH", Abrv3 = "KHM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 120, Name = "Cameroon", Description = "Cameroon", Abrv2 = "CM", Abrv3 = "CMR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 124, Name = "Canada", Description = "Canada", Abrv2 = "CA", Abrv3 = "CAN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 136, Name = "Cayman Islands", Description = "Cayman Islands", Abrv2 = "KY", Abrv3 = "CYM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 140, Name = "Central African Republic", Description = "Central African Republic", Abrv2 = "CF", Abrv3 = "CAF", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 148, Name = "Chad", Description = "Chad", Abrv2 = "TD", Abrv3 = "TCD", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 152, Name = "Chile", Description = "Chile", Abrv2 = "CL", Abrv3 = "CHL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 156, Name = "China", Description = "China", Abrv2 = "CN", Abrv3 = "CHN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 162, Name = "Christmas Island", Description = "Christmas Island", Abrv2 = "CX", Abrv3 = "CXR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 166, Name = "Cocos (Keeling) Islands", Description = "Cocos (Keeling) Islands", Abrv2 = "CC", Abrv3 = "CCK", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 170, Name = "Colombia", Description = "Colombia", Abrv2 = "CO", Abrv3 = "COL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 174, Name = "Comoros", Description = "Comoros", Abrv2 = "KM", Abrv3 = "COM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 178, Name = "Congo", Description = "Congo", Abrv2 = "CG", Abrv3 = "COG", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 180, Name = "Congo (Democratic Republic of the)", Description = "Congo (Democratic Republic of the)", Abrv2 = "CD", Abrv3 = "COD", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 184, Name = "Cook Islands", Description = "Cook Islands", Abrv2 = "CK", Abrv3 = "COK", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 188, Name = "Costa Rica", Description = "Costa Rica", Abrv2 = "CR", Abrv3 = "CRI", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 384, Name = "Cote d'Ivoire", Description = "Cote d'Ivoire", Abrv2 = "CI", Abrv3 = "CIV", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 191, Name = "Croatia", Description = "Croatia", Abrv2 = "HR", Abrv3 = "HRV", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 192, Name = "Cuba", Description = "Cuba", Abrv2 = "CU", Abrv3 = "CUB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 193, Name = "Curacao", Description = "Curacao", Abrv2 = "CW", Abrv3 = "CUW", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 196, Name = "Cyprus", Description = "Cyprus", Abrv2 = "CY", Abrv3 = "CYP", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 203, Name = "Czechia", Description = "Czechia", Abrv2 = "CZ", Abrv3 = "CZE", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 208, Name = "Denmark", Description = "Denmark", Abrv2 = "DK", Abrv3 = "DNK", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 262, Name = "Djibouti", Description = "Djibouti", Abrv2 = "DJ", Abrv3 = "DJI", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 212, Name = "Dominica", Description = "Dominica", Abrv2 = "DM", Abrv3 = "DMA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 214, Name = "Dominican Republic", Description = "Dominican Republic", Abrv2 = "DO", Abrv3 = "DOM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 218, Name = "Ecuador", Description = "Ecuador", Abrv2 = "EC", Abrv3 = "ECU", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 818, Name = "Egypt", Description = "Egypt", Abrv2 = "EG", Abrv3 = "EGY", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 222, Name = "El Salvador", Description = "El Salvador", Abrv2 = "SV", Abrv3 = "SLV", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 226, Name = "Equatorial Guinea", Description = "Equatorial Guinea", Abrv2 = "GQ", Abrv3 = "GNQ", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 232, Name = "Eritrea", Description = "Eritrea", Abrv2 = "ER", Abrv3 = "ERI", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 233, Name = "Estonia", Description = "Estonia", Abrv2 = "EE", Abrv3 = "EST", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 748, Name = "Eswatini", Description = "Eswatini", Abrv2 = "SZ", Abrv3 = "SWZ", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 231, Name = "Ethiopia", Description = "Ethiopia", Abrv2 = "ET", Abrv3 = "ETH", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 238, Name = "Falkland Islands", Description = "Falkland Islands", Abrv2 = "FK", Abrv3 = "FLK", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 234, Name = "Faroe Islands", Description = "Faroe Islands", Abrv2 = "FO", Abrv3 = "FRO", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 242, Name = "Fiji", Description = "Fiji", Abrv2 = "FJ", Abrv3 = "FJI", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 246, Name = "Finland", Description = "Finland", Abrv2 = "FI", Abrv3 = "FIN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 250, Name = "France", Description = "France", Abrv2 = "FR", Abrv3 = "FRA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 254, Name = "French Guiana", Description = "French Guiana", Abrv2 = "GF", Abrv3 = "GUF", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 258, Name = "French Polynesia", Description = "French Polynesia", Abrv2 = "PF", Abrv3 = "PYF", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 260, Name = "French Southern Territories", Description = "French Southern Territories", Abrv2 = "TF", Abrv3 = "ATF", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 266, Name = "Gabon", Description = "Gabon", Abrv2 = "GA", Abrv3 = "GAB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 270, Name = "Gambia", Description = "Gambia", Abrv2 = "GM", Abrv3 = "GMB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 268, Name = "Georgia", Description = "Georgia", Abrv2 = "GE", Abrv3 = "GEO", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 276, Name = "Germany", Description = "Germany", Abrv2 = "DE", Abrv3 = "DEU", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 288, Name = "Ghana", Description = "Ghana", Abrv2 = "GH", Abrv3 = "GHA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 292, Name = "Gibraltar", Description = "Gibraltar", Abrv2 = "GI", Abrv3 = "GIB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 300, Name = "Greece", Description = "Greece", Abrv2 = "GR", Abrv3 = "GRC", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 304, Name = "Greenland", Description = "Greenland", Abrv2 = "GL", Abrv3 = "GRL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 308, Name = "Grenada", Description = "Grenada", Abrv2 = "GD", Abrv3 = "GRD", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 312, Name = "Guadeloupe", Description = "Guadeloupe", Abrv2 = "GP", Abrv3 = "GLP", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 316, Name = "Guam", Description = "Guam", Abrv2 = "GU", Abrv3 = "GUM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 320, Name = "Guatemala", Description = "Guatemala", Abrv2 = "GT", Abrv3 = "GTM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 325, Name = "Guernsey", Description = "Guernsey", Abrv2 = "GG", Abrv3 = "GGY", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 324, Name = "Guinea", Description = "Guinea", Abrv2 = "GN", Abrv3 = "GIN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 624, Name = "Guinea-Bissau", Description = "Guinea-Bissau", Abrv2 = "GW", Abrv3 = "GNB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 328, Name = "Guyana", Description = "Guyana", Abrv2 = "GY", Abrv3 = "GUY", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 332, Name = "Haiti", Description = "Haiti", Abrv2 = "HT", Abrv3 = "HTI", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 334, Name = "Heard Island and McDonald Islands", Description = "Heard Island and McDonald Islands", Abrv2 = "HM", Abrv3 = "HMD", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 336, Name = "Holy See", Description = "Holy See", Abrv2 = "VA", Abrv3 = "VAT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 340, Name = "Honduras", Description = "Honduras", Abrv2 = "HN", Abrv3 = "HND", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 344, Name = "Hong Kong", Description = "Hong Kong", Abrv2 = "HK", Abrv3 = "HKG", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 348, Name = "Hungary", Description = "Hungary", Abrv2 = "HU", Abrv3 = "HUN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 352, Name = "Iceland", Description = "Iceland", Abrv2 = "IS", Abrv3 = "ISL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 356, Name = "India", Description = "India", Abrv2 = "IN", Abrv3 = "IND", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 360, Name = "Indonesia", Description = "Indonesia", Abrv2 = "ID", Abrv3 = "IDN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 364, Name = "Iran", Description = "Iran", Abrv2 = "IR", Abrv3 = "IRN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 368, Name = "Iraq", Description = "Iraq", Abrv2 = "IQ", Abrv3 = "IRQ", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 372, Name = "Ireland", Description = "Ireland", Abrv2 = "IE", Abrv3 = "IRL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 353, Name = "Isle of Man", Description = "Isle of Man", Abrv2 = "IM", Abrv3 = "IMN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 376, Name = "Israel", Description = "Israel", Abrv2 = "IL", Abrv3 = "ISR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 380, Name = "Italy", Description = "Italy", Abrv2 = "IT", Abrv3 = "ITA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 388, Name = "Jamaica", Description = "Jamaica", Abrv2 = "JM", Abrv3 = "JAM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 392, Name = "Japan", Description = "Japan", Abrv2 = "JP", Abrv3 = "JPN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 393, Name = "Jersey", Description = "Jersey", Abrv2 = "JE", Abrv3 = "JEY", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 400, Name = "Jordan", Description = "Jordan", Abrv2 = "JO", Abrv3 = "JOR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 398, Name = "Kazakhstan", Description = "Kazakhstan", Abrv2 = "KZ", Abrv3 = "KAZ", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 404, Name = "Kenya", Description = "Kenya", Abrv2 = "KE", Abrv3 = "KEN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 296, Name = "Kiribati", Description = "Kiribati", Abrv2 = "KI", Abrv3 = "KIR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 408, Name = "Korea (Democratic People's Republic of)", Description = "Korea (Democratic People's Republic of)", Abrv2 = "KP", Abrv3 = "PRK", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 410, Name = "Korea (Republic of)", Description = "Korea (Republic of)", Abrv2 = "KR", Abrv3 = "KOR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 414, Name = "Kuwait", Description = "Kuwait", Abrv2 = "KW", Abrv3 = "KWT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 417, Name = "Kyrgyzstan", Description = "Kyrgyzstan", Abrv2 = "KG", Abrv3 = "KGZ", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 418, Name = "Lao People's Democratic Republic", Description = "Lao People's Democratic Republic", Abrv2 = "LA", Abrv3 = "LAO", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 428, Name = "Latvia", Description = "Latvia", Abrv2 = "LV", Abrv3 = "LVA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 422, Name = "Lebanon", Description = "Lebanon", Abrv2 = "LB", Abrv3 = "LBN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 426, Name = "Lesotho", Description = "Lesotho", Abrv2 = "LS", Abrv3 = "LSO", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 430, Name = "Liberia", Description = "Liberia", Abrv2 = "LR", Abrv3 = "LBR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 434, Name = "Libya", Description = "Libya", Abrv2 = "LY", Abrv3 = "LBY", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 438, Name = "Liechtenstein", Description = "Liechtenstein", Abrv2 = "LI", Abrv3 = "LIE", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 440, Name = "Lithuania", Description = "Lithuania", Abrv2 = "LT", Abrv3 = "LTU", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 442, Name = "Luxembourg", Description = "Luxembourg", Abrv2 = "LU", Abrv3 = "LUX", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 446, Name = "Macao", Description = "Macao", Abrv2 = "MO", Abrv3 = "MAC", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 807, Name = "Macedonia", Description = "Macedonia", Abrv2 = "MK", Abrv3 = "MKD", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 450, Name = "Madagascar", Description = "Madagascar", Abrv2 = "MG", Abrv3 = "MDG", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 454, Name = "Malawi", Description = "Malawi", Abrv2 = "MW", Abrv3 = "MWI", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 458, Name = "Malaysia", Description = "Malaysia", Abrv2 = "MY", Abrv3 = "MYS", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 462, Name = "Maldives", Description = "Maldives", Abrv2 = "MV", Abrv3 = "MDV", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 466, Name = "Mali", Description = "Mali", Abrv2 = "ML", Abrv3 = "MLI", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 470, Name = "Malta", Description = "Malta", Abrv2 = "MT", Abrv3 = "MLT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 584, Name = "Marshall Islands", Description = "Marshall Islands", Abrv2 = "MH", Abrv3 = "MHL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 474, Name = "Martinique", Description = "Martinique", Abrv2 = "MQ", Abrv3 = "MTQ", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 478, Name = "Mauritania", Description = "Mauritania", Abrv2 = "MR", Abrv3 = "MRT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 480, Name = "Mauritius", Description = "Mauritius", Abrv2 = "MU", Abrv3 = "MUS", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 175, Name = "Mayotte", Description = "Mayotte", Abrv2 = "YT", Abrv3 = "MYT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 484, Name = "Mexico", Description = "Mexico", Abrv2 = "MX", Abrv3 = "MEX", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 583, Name = "Micronesia", Description = "Micronesia", Abrv2 = "FM", Abrv3 = "FSM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 498, Name = "Moldova", Description = "Moldova", Abrv2 = "MD", Abrv3 = "MDA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 492, Name = "Monaco", Description = "Monaco", Abrv2 = "MC", Abrv3 = "MCO", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 496, Name = "Mongolia", Description = "Mongolia", Abrv2 = "MN", Abrv3 = "MNG", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 501, Name = "Montenegro", Description = "Montenegro", Abrv2 = "ME", Abrv3 = "MNE", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 500, Name = "Montserrat", Description = "Montserrat", Abrv2 = "MS", Abrv3 = "MSR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 504, Name = "Morocco", Description = "Morocco", Abrv2 = "MA", Abrv3 = "MAR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 508, Name = "Mozambique", Description = "Mozambique", Abrv2 = "MZ", Abrv3 = "MOZ", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 104, Name = "Myanmar", Description = "Myanmar", Abrv2 = "MM", Abrv3 = "MMR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 516, Name = "Namibia", Description = "Namibia", Abrv2 = "NaN", Abrv3 = "NAM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 520, Name = "Nauru", Description = "Nauru", Abrv2 = "NR", Abrv3 = "NRU", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 524, Name = "Nepal", Description = "Nepal", Abrv2 = "NP", Abrv3 = "NPL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 528, Name = "Netherlands", Description = "Netherlands", Abrv2 = "NL", Abrv3 = "NLD", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 530, Name = "Netherlands Antilles", Description = "Netherlands Antilles", Abrv2 = "AN", Abrv3 = "ANT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 540, Name = "New Caledonia", Description = "New Caledonia", Abrv2 = "NC", Abrv3 = "NCL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 554, Name = "New Zealand", Description = "New Zealand", Abrv2 = "NZ", Abrv3 = "NZL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 558, Name = "Nicaragua", Description = "Nicaragua", Abrv2 = "NI", Abrv3 = "NIC", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 562, Name = "Niger", Description = "Niger", Abrv2 = "NE", Abrv3 = "NER", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 566, Name = "Nigeria", Description = "Nigeria", Abrv2 = "NG", Abrv3 = "NGA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 570, Name = "Niue", Description = "Niue", Abrv2 = "NU", Abrv3 = "NIU", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 574, Name = "Norfolk Island", Description = "Norfolk Island", Abrv2 = "NF", Abrv3 = "NFK", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 580, Name = "Northern Mariana Islands", Description = "Northern Mariana Islands", Abrv2 = "MP", Abrv3 = "MNP", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 578, Name = "Norway", Description = "Norway", Abrv2 = "NO", Abrv3 = "NOR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 512, Name = "Oman", Description = "Oman", Abrv2 = "OM", Abrv3 = "OMN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 586, Name = "Pakistan", Description = "Pakistan", Abrv2 = "PK", Abrv3 = "PAK", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 585, Name = "Palau", Description = "Palau", Abrv2 = "PW", Abrv3 = "PLW", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 275, Name = "Palestine, State of", Description = "Palestine, State of", Abrv2 = "PS", Abrv3 = "PSE", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 591, Name = "Panama", Description = "Panama", Abrv2 = "PA", Abrv3 = "PAN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 598, Name = "Papua New Guinea", Description = "Papua New Guinea", Abrv2 = "PG", Abrv3 = "PNG", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 600, Name = "Paraguay", Description = "Paraguay", Abrv2 = "PY", Abrv3 = "PRY", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 604, Name = "Peru", Description = "Peru", Abrv2 = "PE", Abrv3 = "PER", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 608, Name = "Philippines", Description = "Philippines", Abrv2 = "PH", Abrv3 = "PHL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 612, Name = "Pitcairn", Description = "Pitcairn", Abrv2 = "PN", Abrv3 = "PCN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 616, Name = "Poland", Description = "Poland", Abrv2 = "PL", Abrv3 = "POL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 620, Name = "Portugal", Description = "Portugal", Abrv2 = "PT", Abrv3 = "PRT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 630, Name = "Puerto Rico", Description = "Puerto Rico", Abrv2 = "PR", Abrv3 = "PRI", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 634, Name = "Qatar", Description = "Qatar", Abrv2 = "QA", Abrv3 = "QAT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 638, Name = "Reunion", Description = "Reunion", Abrv2 = "RE", Abrv3 = "REU", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 642, Name = "Romania", Description = "Romania", Abrv2 = "RO", Abrv3 = "ROU", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 643, Name = "Russian Federation", Description = "Russian Federation", Abrv2 = "RU", Abrv3 = "RUS", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 646, Name = "Rwanda", Description = "Rwanda", Abrv2 = "RW", Abrv3 = "RWA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 647, Name = "Saint Barthelemy", Description = "Saint Barthelemy", Abrv2 = "BL", Abrv3 = "BLM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 654, Name = "Saint Helena, Ascension and Tristan da Cunha", Description = "Saint Helena, Ascension and Tristan da Cunha", Abrv2 = "SH", Abrv3 = "SHN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 659, Name = "Saint Kitts and Nevis", Description = "Saint Kitts and Nevis", Abrv2 = "KN", Abrv3 = "KNA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 662, Name = "Saint Lucia", Description = "Saint Lucia", Abrv2 = "LC", Abrv3 = "LCA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 655, Name = "Saint Martin", Description = "Saint Martin", Abrv2 = "MF", Abrv3 = "MAF", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 666, Name = "Saint Pierre and Miquelon", Description = "Saint Pierre and Miquelon", Abrv2 = "PM", Abrv3 = "SPM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 670, Name = "Saint Vincent and the Grenadines", Description = "Saint Vincent and the Grenadines", Abrv2 = "VC", Abrv3 = "VCT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 882, Name = "Samoa", Description = "Samoa", Abrv2 = "WS", Abrv3 = "WSM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 674, Name = "San Marino", Description = "San Marino", Abrv2 = "SM", Abrv3 = "SMR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 678, Name = "Sao Tome and Principe", Description = "Sao Tome and Principe", Abrv2 = "ST", Abrv3 = "STP", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 682, Name = "Saudi Arabia", Description = "Saudi Arabia", Abrv2 = "SA", Abrv3 = "SAU", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 686, Name = "Senegal", Description = "Senegal", Abrv2 = "SN", Abrv3 = "SEN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 891, Name = "Serbia", Description = "Serbia", Abrv2 = "RS", Abrv3 = "SRB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 690, Name = "Seychelles", Description = "Seychelles", Abrv2 = "SC", Abrv3 = "SYC", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 694, Name = "Sierra Leone", Description = "Sierra Leone", Abrv2 = "SL", Abrv3 = "SLE", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 702, Name = "Singapore", Description = "Singapore", Abrv2 = "SG", Abrv3 = "SGP", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 656, Name = "Sint Maarten", Description = "Sint Maarten", Abrv2 = "SX", Abrv3 = "SXM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 703, Name = "Slovakia", Description = "Slovakia", Abrv2 = "SK", Abrv3 = "SVK", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 705, Name = "Slovenia", Description = "Slovenia", Abrv2 = "SI", Abrv3 = "SVN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 90, Name = "Solomon Islands", Description = "Solomon Islands", Abrv2 = "SB", Abrv3 = "SLB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 706, Name = "Somalia", Description = "Somalia", Abrv2 = "SO", Abrv3 = "SOM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 710, Name = "South Africa", Description = "South Africa", Abrv2 = "ZA", Abrv3 = "ZAF", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 239, Name = "South Georgia and the South Sandwich Islands", Description = "South Georgia and the South Sandwich Islands", Abrv2 = "GS", Abrv3 = "SGS", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 892, Name = "South Sudan", Description = "South Sudan", Abrv2 = "SS", Abrv3 = "SSD", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 724, Name = "Spain", Description = "Spain", Abrv2 = "ES", Abrv3 = "ESP", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 144, Name = "Sri Lanka", Description = "Sri Lanka", Abrv2 = "LK", Abrv3 = "LKA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 736, Name = "Sudan", Description = "Sudan", Abrv2 = "SD", Abrv3 = "SDN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 740, Name = "Suriname", Description = "Suriname", Abrv2 = "SR", Abrv3 = "SUR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 744, Name = "Svalbard and Jan Mayen", Description = "Svalbard and Jan Mayen", Abrv2 = "SJ", Abrv3 = "SJM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 752, Name = "Sweden", Description = "Sweden", Abrv2 = "SE", Abrv3 = "SWE", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 756, Name = "Switzerland", Description = "Switzerland", Abrv2 = "CH", Abrv3 = "CHE", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 760, Name = "Syrian Arab Republic", Description = "Syrian Arab Republic", Abrv2 = "SY", Abrv3 = "SYR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 158, Name = "Taiwan", Description = "Taiwan", Abrv2 = "TW", Abrv3 = "TWN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 762, Name = "Tajikistan", Description = "Tajikistan", Abrv2 = "TJ", Abrv3 = "TJK", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 834, Name = "Tanzania, United Republic of", Description = "Tanzania, United Republic of", Abrv2 = "TZ", Abrv3 = "TZA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 764, Name = "Thailand", Description = "Thailand", Abrv2 = "TH", Abrv3 = "THA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 626, Name = "Timor-Leste", Description = "Timor-Leste", Abrv2 = "TL", Abrv3 = "TLS", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 768, Name = "Togo", Description = "Togo", Abrv2 = "TG", Abrv3 = "TGO", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 772, Name = "Tokelau", Description = "Tokelau", Abrv2 = "TK", Abrv3 = "TKL", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 776, Name = "Tonga", Description = "Tonga", Abrv2 = "TO", Abrv3 = "TON", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 780, Name = "Trinidad and Tobago", Description = "Trinidad and Tobago", Abrv2 = "TT", Abrv3 = "TTO", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 788, Name = "Tunisia", Description = "Tunisia", Abrv2 = "TN", Abrv3 = "TUN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 792, Name = "Turkey", Description = "Turkey", Abrv2 = "TR", Abrv3 = "TUR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 795, Name = "Turkmenistan", Description = "Turkmenistan", Abrv2 = "TM", Abrv3 = "TKM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 796, Name = "Turks and Caicos Islands", Description = "Turks and Caicos Islands", Abrv2 = "TC", Abrv3 = "TCA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 798, Name = "Tuvalu", Description = "Tuvalu", Abrv2 = "TV", Abrv3 = "TUV", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 800, Name = "Uganda", Description = "Uganda", Abrv2 = "UG", Abrv3 = "UGA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 804, Name = "Ukraine", Description = "Ukraine", Abrv2 = "UA", Abrv3 = "UKR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 784, Name = "United Arab Emirates", Description = "United Arab Emirates", Abrv2 = "AE", Abrv3 = "ARE", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 826, Name = "United Kingdom", Description = "United Kingdom", Abrv2 = "GB", Abrv3 = "GBR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 581, Name = "United States Minor Outlying Islands", Description = "United States Minor Outlying Islands", Abrv2 = "UM", Abrv3 = "UMI", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 840, Name = "United States", Description = "United States of America", Abrv2 = "US", Abrv3 = "USA", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 858, Name = "Uruguay", Description = "Uruguay", Abrv2 = "UY", Abrv3 = "URY", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 860, Name = "Uzbekistan", Description = "Uzbekistan", Abrv2 = "UZ", Abrv3 = "UZB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 548, Name = "Vanuatu", Description = "Vanuatu", Abrv2 = "VU", Abrv3 = "VUT", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 862, Name = "Venezuela", Description = "Venezuela", Abrv2 = "VE", Abrv3 = "VEN", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 704, Name = "Viet Nam", Description = "Viet Nam", Abrv2 = "VN", Abrv3 = "VNM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 92, Name = "Virgin Islands (British)", Description = "Virgin Islands (British)", Abrv2 = "VG", Abrv3 = "VGB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 850, Name = "Virgin Islands (U.S.)", Description = "Virgin Islands (U.S.)", Abrv2 = "VI", Abrv3 = "VIR", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 876, Name = "Wallis and Futuna", Description = "Wallis and Futuna", Abrv2 = "WF", Abrv3 = "WLF", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 732, Name = "Western Sahara", Description = "Western Sahara", Abrv2 = "EH", Abrv3 = "ESH", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 887, Name = "Yemen", Description = "Yemen", Abrv2 = "YE", Abrv3 = "YEM", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 894, Name = "Zambia", Description = "Zambia", Abrv2 = "ZM", Abrv3 = "ZMB", CreatedAt = seedAt, UpdatedAt = seedAt },
            new Country { Id = 716, Name = "Zimbabwe", Description = "Zimbabwe", Abrv2 = "ZW", Abrv3 = "ZWE", CreatedAt = seedAt, UpdatedAt = seedAt }
            );
        }
    }
}